# Generated by Django 4.0.5 on 2022-06-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patisseriettj', '0002_clients_viennoiserie_patisserie_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucrerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(null=True)),
                ('url', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='patisserie',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='viennoiserie',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
