# Generated by Django 4.0.5 on 2022-06-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patisseriettj', '0004_alter_patisserie_price_alter_sucrerie_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
