# Generated by Django 4.0.5 on 2022-06-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patisseriettj', '0005_rename_clients_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
